/**
 * Aggregated per-tool authorization policy table.
 *
 * Every MCP tool has an explicit entry. The MCP server enforces the
 * *interface-level* policy (authentication, role gating for tools/list
 * visibility, confirmation labeling). The *data-level* authorization is
 * enforced by the backend.
 */

import type { ToolPolicy } from './contracts.js';

export const TOOL_POLICIES: Record<string, ToolPolicy> = {
  // --- User/account ---
  get_user_info: {
    capability: 'view_account',
    requiresEntitlement: false,
    classifications: ['READ'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  update_student: {
    capability: 'view_account',
    requiresEntitlement: false,
    classifications: ['WRITE', 'PRIVACY_SENSITIVE'],
    requiredRoles: [],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },

  // --- Wallet ---
  get_wallet_balance: {
    capability: 'view_balance',
    requiresEntitlement: false,
    classifications: ['READ', 'PRIVACY_SENSITIVE'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  get_wallet_status: {
    capability: 'view_balance',
    requiresEntitlement: false,
    classifications: ['READ', 'PRIVACY_SENSITIVE'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  top_up_balance: {
    capability: 'view_balance',
    requiresEntitlement: true,
    classifications: ['FINANCIAL', 'WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: true,
    destructive: false,
    requiresConfirmation: true,
  },
  donate_to_school: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['FINANCIAL', 'WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: true,
    destructive: false,
    requiresConfirmation: true,
  },

  // --- Orders ---
  order_lunch: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['FINANCIAL', 'WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: true,
    destructive: false,
    requiresConfirmation: true,
  },
  get_orders: {
    capability: 'view_orders',
    requiresEntitlement: false,
    classifications: ['READ'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  get_daily_menu: {
    capability: 'view_menu',
    requiresEntitlement: false,
    classifications: ['READ'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  create_draft_order: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['FINANCIAL', 'WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: true,
    destructive: false,
    requiresConfirmation: true,
  },
  finalize_order: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['FINANCIAL', 'WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: true,
    destructive: false,
    requiresConfirmation: true,
  },
  cancel_order: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['DESTRUCTIVE', 'WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: false,
    destructive: true,
    requiresConfirmation: true,
  },
  get_updates: {
    capability: 'view_orders',
    requiresEntitlement: false,
    classifications: ['READ'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  get_daily_orders: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['READ', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'lunch_cordinator'],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  get_monthly_orders: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['READ', 'ADMIN'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },

  // --- Events ---
  get_upcoming_events: {
    capability: 'view_events',
    requiresEntitlement: false,
    classifications: ['READ'],
    requiredRoles: [],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  create_event: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['WRITE', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'event_cordinator'],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },
  update_event: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['WRITE', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'event_cordinator'],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },
  cancel_event: {
    capability: 'ai_write',
    requiresEntitlement: true,
    classifications: ['DESTRUCTIVE', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'event_cordinator'],
    mutates: true,
    financial: false,
    destructive: true,
    requiresConfirmation: true,
  },
  register_event: {
    capability: 'ai_write',
    requiresEntitlement: false,
    classifications: ['WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },
  request_volunteer: {
    capability: 'ai_write',
    requiresEntitlement: false,
    classifications: ['WRITE'],
    requiredRoles: [],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },

  // --- Admin: restaurants ---
  list_school_restaurants: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['READ', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'pac_member', 'lunch_cordinator'],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  create_restaurant: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['WRITE', 'ADMIN'],
    requiredRoles: ['pac_cordinator'],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },

  // --- Admin: menu ---
  list_menu_items: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['READ', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'lunch_cordinator'],
    mutates: false,
    financial: false,
    destructive: false,
    requiresConfirmation: false,
  },
  create_menu_item: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['WRITE', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'lunch_cordinator'],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },
  update_menu_item: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['WRITE', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'lunch_cordinator'],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },
  set_menu_item_price: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['WRITE', 'ADMIN', 'FINANCIAL'],
    requiredRoles: ['pac_cordinator', 'lunch_cordinator'],
    mutates: true,
    financial: true,
    destructive: false,
    requiresConfirmation: true,
  },
  delete_menu_item: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['DESTRUCTIVE', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'lunch_cordinator'],
    mutates: true,
    financial: false,
    destructive: true,
    requiresConfirmation: true,
  },
  set_daily_menu: {
    capability: null,
    requiresEntitlement: false,
    classifications: ['WRITE', 'ADMIN'],
    requiredRoles: ['pac_cordinator', 'lunch_cordinator'],
    mutates: true,
    financial: false,
    destructive: false,
    requiresConfirmation: true,
  },
};
